name: Deploy Taquilla Web to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying web application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/operadora-taquilla-web
            cd /opt/operadora-taquilla-web
            if [ ! -d ".git" ]; then
              git clone https://github.com/andyfuenmayor-droid/operadora-taquilla-web.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            bash deploy.sh
